name: pasanaku
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  dio: ^5.4.2+1
  firebase_core: ^2.30.0
  firebase_messaging: ^14.8.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.5.1
  go_router: ^13.2.2
  google_fonts: ^6.2.1
  http: ^1.2.1
  shared_preferences: ^2.2.3
  image_picker: ^0.8.1+4

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/logo_pasanaku.png
    - assets/qr_scanner.jpg
