// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS9Kch-HrZO5f8Tq6t2PnehI2s1Jql1Ws',
    appId: '1:411120248830:web:51505bde016cdbe5c542af',
    messagingSenderId: '411120248830',
    projectId: 'pasanaku-6a187',
    authDomain: 'pasanaku-6a187.firebaseapp.com',
    storageBucket: 'pasanaku-6a187.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAExUOeLlQWAGaOGoZyWBCIcAPBj0ZQft8',
    appId: '1:411120248830:android:de33b0f837e301d6c542af',
    messagingSenderId: '411120248830',
    projectId: 'pasanaku-6a187',
    storageBucket: 'pasanaku-6a187.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANBW9ExtoUjGOzD8KSTEKu-QR-NFdaFXg',
    appId: '1:411120248830:ios:de6d1368dc07b904c542af',
    messagingSenderId: '411120248830',
    projectId: 'pasanaku-6a187',
    storageBucket: 'pasanaku-6a187.appspot.com',
    iosBundleId: 'com.example.pasanaku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANBW9ExtoUjGOzD8KSTEKu-QR-NFdaFXg',
    appId: '1:411120248830:ios:de6d1368dc07b904c542af',
    messagingSenderId: '411120248830',
    projectId: 'pasanaku-6a187',
    storageBucket: 'pasanaku-6a187.appspot.com',
    iosBundleId: 'com.example.pasanaku',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBS9Kch-HrZO5f8Tq6t2PnehI2s1Jql1Ws',
    appId: '1:411120248830:web:d688d7f4dc591e2fc542af',
    messagingSenderId: '411120248830',
    projectId: 'pasanaku-6a187',
    authDomain: 'pasanaku-6a187.firebaseapp.com',
    storageBucket: 'pasanaku-6a187.appspot.com',
  );
}
